name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f Backend/requirements.txt ]; then pip install -r Backend/requirements.txt; fi

      - name: Analysing the code with pylint
        run: |
          pylint Backend
